### ISSUE TITLE
Mistake in german translation

### ISSUE THREAD

**Issue by DarkwingDucky** [linuxmint/mintdrivers#67]
In the _mintdrivers-de.po_, line 140, "Ihr Rechner benötigt einige zusätzliche Treiber." is wrong. A right translation would be:
"Ihr Rechner benötigt keine zusätzlichen Treiber."
This is irritating and confusing many users, because the existing line means:
"Your computer does need several additional drivers."
instead of 
"Your computer does not need any additional drivers."

**Comment by to-ba** [comment]
Fixed on Launchpad.

@clefebvre please update the translation file.

**Comment by hduelme** [comment]
This is fixed in the current version. So this issue should be closed.

**Comment by DarkwingDucky** [comment]
Thank you very much!

**Comment by DarkwingDucky** [comment]
The Problem still exists in Linux Mint 20.2 Uma.
Too difficult to update the package?

**Comment by clefebvre** [comment]
1.6.3 was backported to all supported releases.
